baseURL = "https://skillbox-manuals.github.io/manuals/"
languageCode = "ru-ru"
title = "Skillbox Manuals"
theme = "book"

[params]
# (Optional, default true) Enables search function with flexsearch,
# Index is built on fly, therefore it might slowdown your website.
# Configuration for indexing can be adjusted in i18n folder per language.
BookSearch = false

